### ISSUE TITLE
[question] How old is the code?

### ISSUE THREAD

**Issue by inlife** [Southclaw/scdm#1]
How old is the code?

> So I figured I may as well release it as open source since I still own the IP!

Maybe now, after all these years(?), after you've made it open, you will finally finish it :D

**Comment by Southclaws** [comment]
I think it's 2 or 3 years old, I can't even remember! Maybe I will finish it, all the module API is done and I think user accounts work. I may think about updating it a bit since I've learnt a hell of a lot more since I wrote it originally!

**Comment by inlife** [comment]
> I've learnt a hell of a lot more since I wrote it originally!

I believe now you can even reverse engineer sa-mp and write your gamemode on pure c++ :DD
Because why not!

**Comment by Southclaws** [comment]
That would be interesting...

I like the Pawn language too much though! I'm even [planning](http://forum.sa-mp.com/showthread.php?t=613510) to write a static analysis tool for it!

**Comment by inlife** [comment]
Wow, didn't know that 🙌 

As far as i can tell, from my own experience writing a lexer (tokenizer) is quite simple task. But even at that point after tokenization, you can use simple look-ahead operations to check for existing/non-existing semicolon/comma/etc.

As for scope-aware analyzer for pawn, man oh man. I'll start praying for your soul! :DD

**Comment by Southclaws** [comment]
Yeah I could easily add missing semicolon highlighting to the Sublime Text plugin. But that's boring!
